import { imageWidths } from "~/data/imageWidths";

/**
 * srcset for an image that has web-sized variants (`foo-2400.webp` +
 * `foo-1200.webp`, generated by `scripts/compress-images.mjs --resize`).
 * Returns undefined for any other src, so the plain `src` is used.
 */
export function srcSet(src: string | undefined): string | undefined {
  if (!src?.endsWith("-2400.webp")) return undefined;
  const small = src.replace(/-2400\.webp$/, "-1200.webp");
  const large = imageWidths[src];
  const smallWidth = imageWidths[small];
  if (!large || !smallWidth) return undefined;
  return `${small} ${smallWidth}w, ${src} ${large}w`;
}
